### ISSUE TITLE
Bug in rendering?

### ISSUE THREAD

**Issue by whytong** [Acylation/obsidian-chem#19]
### What happened?

I tried to embed the chemical structure of DTNB and it seems the plugin does not render the structure properly in certain cases. Particularly, I tried two SMILES of the same molecule, one seems to work, one seems to miss one oxygen.
This one works:
```smiles
C1=CC(=C(C=C1SSC2=CC(=C(C=C2)[N+](=O)[O-])C(=O)O)C(=O)O)[N+](=O)[O-]
```

This one is missing an oxygen in the nitro group.
```smiles
O=C(O)C1=C([N+]([O-])=O)C=CC(SSC2=CC(C(O)=O)=C([N+]([O-])=O)C=C2)=C1
```

### What did you expect to happen?

Both should have two N(+)O2 groups 

### How can we reproduce it (as minimally and precisely as possible)?

paste the two smiles snippets to obsidian.

### Plugin version

0.1.2

### Obsidian version

1.3.5

**Comment by Acylation** [comment]
Yeah I tested it just now. This seems to be a image sizing problem in the upperstream package, smiles-drawer. You can also try your smiles strings out here: https://smilesdrawer.surge.sh/playground.html

There's an option called `compact draw`, with it enabled, the caboxylic group wood be rendered as `COOH` and the nitro group would be rendered as `N+O2` (actually this is also kind of unreasonable)
<img width="683" alt="image1" src="https://github.com/Acylation/obsidian-chem/assets/73122375/247eef16-862d-4932-965b-988471d7e845">

However, when it comes to the original structure, that is, to disable the `compact draw`, you will get following structures. So the problem may take place in the resizing process.
<img width="683" alt="image2" src="https://github.com/Acylation/obsidian-chem/assets/73122375/530296fa-14a1-4aff-b683-16e52252b014">

I just finish my finals and return to my keyboard. I will submit a issue to the smiles-drawer repo, and provide options for compact draw, as mentioned [in the forum](https://forum.obsidian.md/t/smiles-in-obsidian/35974/12)
