### ISSUE TITLE
Update and install failed

### ISSUE THREAD

**Issue by merlinuwe** [Acylation/obsidian-chem#30]
### What happened?

Thanks for your great plugin.

I tried to update the plugin, but it failed. Windows 10, newest updates and newest Obsidian.

Uninstalling and reinstalling didn't work, too. 

![image](https://github.com/Acylation/obsidian-chem/assets/4138869/99a29e30-a190-43bf-951e-d4261f7760e3)

It seems that there is a new release 0.2.0 on the way? 

### What did you expect to happen?

-

### How can we reproduce it (as minimally and precisely as possible)?

-

### Plugin version

newest

### Obsidian version

newest

**Comment by Acylation** [comment]
Thank you for the report. Due to a network issue, the new release failed to upload earlier. It should be working now, so please try installing the new version again.

**Comment by merlinuwe** [comment]
Yes, now it works. Thank you very much for your fast response.
