### ISSUE TITLE
Reaction symbol ">>" is not being rendered

### ISSUE THREAD

**Issue by jxsoares** [Acylation/obsidian-chem#31]
### What happened?

The symbol ">>" is no longer being rendered.

### What did you expect to happen?

The symbol ">>" rendered as a forward arrow.

### How can we reproduce it (as minimally and precisely as possible)?

Example:
```smiles
[HH].CC(C)CC1=CC=C(C(C)=O)C=C1>>CC(C)CC2=CC=C(C(C)O)C=C2
```
Produces:
SyntaxError
Expected "%", "(", "*", "B", "C", "[", [0-9], [NOPSFI], [\-=#$:/\\.], [bcnops], or end of input but ">" found.

### Anything else we need to know?

On the previous version the ">>" was working as expected.

### Plugin version

0.2.0

### Obsidian version

1.4.2

**Comment by Acylation** [comment]
Yeah it should be supported. Thanks for the report and will look into this.

**Comment by Acylation** [comment]
Hi! This should be fixed in the new release. Feel free to comment if the problem persists.

**Comment by jxsoares** [comment]
It's working 👍 Thank you very much!
