### ISSUE TITLE
Inline render and Annotating molecules

### ISSUE THREAD

**Issue by craldaz** [Acylation/obsidian-chem#42]
### What would you like to be added?

I would like to be able to make tables of molecules using Markdown tables

| Name  | Data | Molecule |
|-------|-----|------------|
| propane | 30  | ```smiles CCC```|

Or using dataview tables e.g.

Propane.md
Name:: propane
Smiles:: ```CCC```
Data:: 30

It would also be nice to annotate molecules for example if i gave obsidian chem a list of smiles with multiple columns it would interpret these as names, or other info -- this may be the simplest way to implement something immediately. 

### Why is this needed?

More powerful visualization of chemical structures and data.

**Comment by Acylation** [comment]
Thanks for the idea presented in #43, here's a way using inline DataviewJS to simulate a code block, where you can have the structure rendered in the table cells.

![image](https://github.com/Acylation/obsidian-chem/assets/73122375/aa49791c-be9e-409c-b1f5-051551066ba6)

Insipred by the inline DQL and DataviewJS, I now have a clearer design for `inline-smiles`, with the prefix configurable.

**Comment by craldaz** [comment]
Thanks

**Comment by Acylation** [comment]
Hi @craldaz! I saw your feedback in #43. If you like the flexible feeling powered by the dataview than you can follow that syntax. Otherwise I'm working on a direct inline annotation for smiles, something like `$smiles=c1cccccc1` and the prefix would be configurable.
