### ISSUE TITLE
Convert to Image

### ISSUE THREAD

**Issue by Developer-Mike** [Acylation/obsidian-chem#44]
### What would you like to be added?

It would be cool if you could convert the smiles formula to an SVG or PNG.

### Why is this needed?

This would simplify the process of exporting notes from obsidian.

**Comment by Acylation** [comment]
Yeah convert to image would be a useful feature. However, I am not quite sure if this is related to markdown file exporting, as we can already generate PDF documents containing the structures simply through the official md export. Can you explain more on your use case?

**Comment by Developer-Mike** [comment]
My goal is to export them to a PowerPoint presentation. I currently need to open developer tools in Obsidian, then I need to copy the SVG and after that, I need to convert the SVG to a PNG because SVG fonts don't work in PowerPoint. The molecule isn't correctly centered if I would take a screenshot.
I think this would be a rather simple QOL addition.

**Comment by Acylation** [comment]
Thanks for the clarification, I can get it now. It would be a straight forward implementation.

**Comment by Acylation** [comment]
Hi! This feature is available in the latest 0.3.0 release. You can update the plugin, and right-click on the target image to find the `Copy` button. Further suggestions and feedbacks are warmly welcomed!
